INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_TESTINGGNURADIO testinggnuradio)

FIND_PATH(
    TESTINGGNURADIO_INCLUDE_DIRS
    NAMES testinggnuradio/api.h
    HINTS $ENV{TESTINGGNURADIO_DIR}/include
        ${PC_TESTINGGNURADIO_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    TESTINGGNURADIO_LIBRARIES
    NAMES gnuradio-testinggnuradio
    HINTS $ENV{TESTINGGNURADIO_DIR}/lib
        ${PC_TESTINGGNURADIO_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TESTINGGNURADIO DEFAULT_MSG TESTINGGNURADIO_LIBRARIES TESTINGGNURADIO_INCLUDE_DIRS)
MARK_AS_ADVANCED(TESTINGGNURADIO_LIBRARIES TESTINGGNURADIO_INCLUDE_DIRS)

